UNDEF = -1

DEFAULT_AUTO_CONNECT = False
DEFAULT_WIRELESS_ADDRESS = "192.168.1.1"

DEFAULT_EXEC_ON_CONNECT = False
DEFAULT_CMD = '#'

SAMPLE_CONFIG = ".def.conf"
IGNORE_CONFIG_SECTIONS = ['global', 'INFO']
